/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.schoolmanagment;
import com.Daos.ClassDao;
import com.Daos.StaffDao;
import com.Daos.StudentDao;
import com.Entities.Admin;
import com.Entities.Student;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import com.Entities.Fees;
import java.text.SimpleDateFormat;
import javax.swing.table.TableModel;
import com.Entities.Staff;
/**
 *
 * @author DELL
 */
public class AdminDashboard extends javax.swing.JFrame {
    private static Admin admin;
    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        this.setTitle("Admin's Dashboard");
        jLabel2.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("../assets/Daco_4363443.png")).getImage().getScaledInstance(80, 50, Image.SCALE_SMOOTH)));    
        jLabel3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.setResizable(false);
        this.setBounds(300,100,805,588);
        btn1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn4.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn6.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn5.setCursor(new Cursor(Cursor.HAND_CURSOR));
        tab1.setVisible(false);
        tab2.setVisible(false);
        tab3.setVisible(false);
        tab4.setVisible(false);
        tab5.setVisible(false);
        tab7.setVisible(true);
        tab8.setVisible(false);
    }
    
    public AdminDashboard(Admin admin){
        this();
        AdminDashboard.admin=admin;
        jLabel1.setText(admin.getName().split(" ")[0]);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JLabel();
        btn4 = new javax.swing.JLabel();
        btn3 = new javax.swing.JLabel();
        btn6 = new javax.swing.JLabel();
        btn5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        dob = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        fname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        name = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        mname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        pmobile = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        aadhar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        sssmid = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        occupation = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        tab7 = new javax.swing.JPanel();
        tab2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        dob1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        name1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        fathusname = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        mobile = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        qualification = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        address1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        tab3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        fees_name = new javax.swing.JTextField();
        fee_dob = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        showEdit = new javax.swing.JPanel();
        enrollment = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        receipt_no = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        installmentno = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        due_cleared = new javax.swing.JRadioButton();
        due_not = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        installment_amount = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        fees_name1 = new javax.swing.JTextField();
        fee_dob1 = new javax.swing.JTextField();
        editButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        addmissiondt = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        upfathern = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        upmothern = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        upfathermob = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        upfatheroc = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        upaadhar = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        upsssmid = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        upaddress = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        tcdate = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        tab8 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 110, 70));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 150, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("LOGOUT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("School Management System");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 70));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Admin");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 60, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn2.setBackground(new java.awt.Color(153, 0, 153));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 204, 204));
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn2.setText("Add Student");
        btn2.setOpaque(true);
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 50));

        btn1.setBackground(new java.awt.Color(153, 0, 153));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 204, 204));
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn1.setText("Add Teacher");
        btn1.setOpaque(true);
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 180, 50));

        btn4.setBackground(new java.awt.Color(153, 0, 153));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 204, 204));
        btn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn4.setText("Student Fees");
        btn4.setOpaque(true);
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, 50));

        btn3.setBackground(new java.awt.Color(153, 0, 153));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 204, 204));
        btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn3.setText("Student Details");
        btn3.setOpaque(true);
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 50));

        btn6.setBackground(new java.awt.Color(153, 0, 153));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 204, 204));
        btn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn6.setText("Update Student");
        btn6.setOpaque(true);
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 180, 50));

        btn5.setBackground(new java.awt.Color(153, 0, 153));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 204, 204));
        btn5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn5.setText("Set Class Teacher");
        btn5.setOpaque(true);
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 180, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 470));

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab1.setBackground(new java.awt.Color(204, 153, 255));
        tab1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox2MousePressed(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        tab1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 180, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("STUDENT FORM");
        tab1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("D.O.B");
        tab1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));
        tab1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 160, 10));

        dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dob.setForeground(new java.awt.Color(102, 0, 102));
        dob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dob.setText("format yyyy/mm/dd");
        dob.setBorder(null);
        dob.setOpaque(false);
        dob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dobMouseClicked(evt);
            }
        });
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        tab1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 160, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Father's Name");
        tab1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 110, 30));
        tab1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 160, 10));

        fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(102, 0, 102));
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.setBorder(null);
        fname.setOpaque(false);
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        tab1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Full Name :");
        tab1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));
        tab1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 160, 10));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(102, 0, 102));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(null);
        name.setOpaque(false);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        tab1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Mother Name");
        tab1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 100, 30));
        tab1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 160, 10));

        mname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mname.setForeground(new java.awt.Color(102, 0, 102));
        mname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mname.setBorder(null);
        mname.setOpaque(false);
        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        tab1.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 160, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Parent Mob.");
        tab1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 30));
        tab1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 160, 10));

        pmobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pmobile.setForeground(new java.awt.Color(102, 0, 102));
        pmobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pmobile.setBorder(null);
        pmobile.setOpaque(false);
        pmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmobileActionPerformed(evt);
            }
        });
        tab1.add(pmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 160, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Aadhar No.");
        tab1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 90, 30));
        tab1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 160, 10));

        aadhar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aadhar.setForeground(new java.awt.Color(102, 0, 102));
        aadhar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aadhar.setBorder(null);
        aadhar.setOpaque(false);
        aadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadharActionPerformed(evt);
            }
        });
        tab1.add(aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 160, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("SSSMID");
        tab1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 90, 30));
        tab1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 160, 10));

        sssmid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sssmid.setForeground(new java.awt.Color(102, 0, 102));
        sssmid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sssmid.setBorder(null);
        sssmid.setOpaque(false);
        sssmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssmidActionPerformed(evt);
            }
        });
        tab1.add(sssmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 160, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Occupation");
        tab1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 90, 30));
        tab1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, 10));

        occupation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        occupation.setForeground(new java.awt.Color(102, 0, 102));
        occupation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        occupation.setBorder(null);
        occupation.setOpaque(false);
        occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationActionPerformed(evt);
            }
        });
        tab1.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 160, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Class");
        tab1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 90, 30));
        tab1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 160, 10));

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(102, 0, 102));
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setBorder(null);
        address.setOpaque(false);
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        tab1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 160, 30));

        jButton1.setBackground(new java.awt.Color(255, 102, 153));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("RESET FORM");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tab1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 160, 60));

        jButton2.setBackground(new java.awt.Color(255, 102, 153));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setText("SUBMIT FORM");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        tab1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 160, 60));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Address");
        tab1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, 30));

        jPanel3.add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        tab7.setBackground(new java.awt.Color(204, 153, 255));
        tab7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(tab7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        tab2.setBackground(new java.awt.Color(204, 153, 255));
        tab2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Teacher's Form");
        tab2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("D.O.B");
        tab2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));
        tab2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 160, 10));

        dob1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dob1.setForeground(new java.awt.Color(102, 0, 102));
        dob1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dob1.setText("format yyyy/mm/dd");
        dob1.setBorder(null);
        dob1.setOpaque(false);
        dob1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dob1MouseClicked(evt);
            }
        });
        dob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob1ActionPerformed(evt);
            }
        });
        tab2.add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 160, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Full Name :");
        tab2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));
        tab2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 160, 10));

        name1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(102, 0, 102));
        name1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name1.setBorder(null);
        name1.setOpaque(false);
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        tab2.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Father's/Husband's Name");
        tab2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 190, 30));
        tab2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 190, 10));

        fathusname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fathusname.setForeground(new java.awt.Color(102, 0, 102));
        fathusname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fathusname.setBorder(null);
        fathusname.setOpaque(false);
        fathusname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathusnameActionPerformed(evt);
            }
        });
        tab2.add(fathusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 190, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Mobile");
        tab2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 90, 30));
        tab2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 160, 10));

        mobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mobile.setForeground(new java.awt.Color(102, 0, 102));
        mobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mobile.setBorder(null);
        mobile.setOpaque(false);
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        tab2.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 160, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Password");
        tab2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 90, 30));
        tab2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 160, 10));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Qualification");
        tab2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 90, 30));
        tab2.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, 10));

        qualification.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qualification.setForeground(new java.awt.Color(102, 0, 102));
        qualification.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qualification.setBorder(null);
        qualification.setOpaque(false);
        qualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualificationActionPerformed(evt);
            }
        });
        tab2.add(qualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 160, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Address");
        tab2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 30));
        tab2.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 160, 10));

        address1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address1.setForeground(new java.awt.Color(102, 0, 102));
        address1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address1.setBorder(null);
        address1.setOpaque(false);
        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });
        tab2.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, 30));

        jButton3.setBackground(new java.awt.Color(255, 102, 153));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton3.setText("RESET FORM");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        tab2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 160, 60));

        jButton4.setBackground(new java.awt.Color(255, 102, 153));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton4.setText("SUBMIT FORM");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        tab2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 160, 60));

        password.setText("PAssword");
        tab2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 160, 30));

        jPanel3.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        tab3.setBackground(new java.awt.Color(204, 153, 255));
        tab3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tab3MouseWheelMoved(evt);
            }
        });
        tab3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Class wise Student List");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 30));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 180, 30));

        jButton5.setText("GET DETAILS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 130, 30));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enrollment", "Fullname", "D.O.B.", "Father's Name", "Mother's Name", "Father's Occupation", "Father's Mobile", "Aadhar No.", "SSSMID", "Addmission Date", "Address", "IsStuding", "TC_Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1190, 300));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 170, 30));

        jScrollPane2.setViewportView(jPanel2);

        tab3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 410));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Student's Academic Details");
        tab3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 330, 70));

        jPanel3.add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        tab4.setBackground(new java.awt.Color(204, 153, 255));
        tab4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Fees Details");
        tab4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 330, 70));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Enter Student Details");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 30));

        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox4MousePressed(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 180, 30));

        jButton6.setText("GET DETAILS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 130, 30));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enrollment", "Class_id", "Installment1", "Receipt1", "Installment2", "Receipt2", "Installment3", "Receipt3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane4.setViewportView(jTable2);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1190, 120));

        fees_name.setText("Enter Name");
        jPanel5.add(fees_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 190, 30));

        fee_dob.setText("yyyy/mm/dd");
        jPanel5.add(fee_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, 30));

        editButton.setText("UPDATE STATUS");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel5.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 140, 40));

        showEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentActionPerformed(evt);
            }
        });
        showEdit.add(enrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 150, 30));

        jLabel12.setText("INSTALLMENT AMOUNT PAID");
        showEdit.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 140, 30));

        receipt_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receipt_noActionPerformed(evt);
            }
        });
        showEdit.add(receipt_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 160, 30));

        jLabel13.setText("RECEIPT NUMBER");
        showEdit.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 90, 30));

        jButton7.setText("SAVE STATUS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        showEdit.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 210, 40));

        jLabel23.setText("INSTALLMENT NO.");
        showEdit.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        installmentno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        showEdit.add(installmentno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        jLabel32.setText("Cleared Due");
        showEdit.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 30));

        buttonGroup1.add(due_cleared);
        due_cleared.setText("Yes");
        showEdit.add(due_cleared, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 30));

        buttonGroup1.add(due_not);
        due_not.setText("No");
        showEdit.add(due_not, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 30));

        jLabel33.setText("Enrollment Number");
        showEdit.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 100, 30));

        installment_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installment_amountActionPerformed(evt);
            }
        });
        showEdit.add(installment_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 150, 30));

        jPanel5.add(showEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 630, 130));

        jTextField1.setEnabled(false);
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, 30));

        jLabel34.setText("Enrollment");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        jScrollPane3.setViewportView(jPanel5);

        tab4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 410));

        jPanel3.add(tab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        tab5.setBackground(new java.awt.Color(204, 153, 255));
        tab5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("Enter Student Details");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 30));

        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox5MousePressed(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 180, 30));

        jButton8.setText("GET DETAILS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 130, 30));

        fees_name1.setText("Enter Name");
        jPanel6.add(fees_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 190, 30));

        fee_dob1.setText("yyyy/mm/dd");
        jPanel6.add(fee_dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, 30));

        editButton1.setText("UPDATE STATUS");
        editButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(editButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 140, 40));

        jTextField2.setEnabled(false);
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, 30));

        jLabel41.setText("Enrollment");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        addmissiondt.setEnabled(false);
        jPanel6.add(addmissiondt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, 30));

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("ADDMISSION DATE");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 30));

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("FATHER NAME");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 120, 30));
        jPanel6.add(upfathern, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, 30));

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("MOTHER NAME");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 120, 30));
        jPanel6.add(upmothern, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 180, 30));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("FATHER MOBILE");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 120, 30));
        jPanel6.add(upfathermob, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 180, 30));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("FATHER OCCUPATION");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 30));
        jPanel6.add(upfatheroc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 180, 30));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("AADHAR NO");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 120, 30));
        jPanel6.add(upaadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 180, 30));

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("SSSMID");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 120, 30));
        jPanel6.add(upsssmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 180, 30));

        upaddress.setColumns(20);
        upaddress.setRows(5);
        jScrollPane6.setViewportView(upaddress);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 180, 80));

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("ADDRESS");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 120, 30));

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("TC_DATE");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 120, 30));

        tcdate.setEnabled(false);
        jPanel6.add(tcdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 180, 30));

        jScrollPane5.setViewportView(jPanel6);

        tab5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 630, 390));

        jLabel46.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("UPDATE STUDENT");
        tab5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 260, 80));

        jPanel3.add(tab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        tab8.setBackground(new java.awt.Color(204, 153, 255));
        tab8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Set Class Teacher");
        tab8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 300, 70));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Class");
        tab8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 120, 40));

        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab8.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 210, 40));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Staff Id");
        tab8.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 40));

        jComboBox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab8.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 210, 40));

        jButton9.setText("UPDATE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        tab8.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 190, 50));

        jPanel3.add(tab8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 620, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void pmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmobileActionPerformed

    private void aadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadharActionPerformed

    private void sssmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssmidActionPerformed

    private void occupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String stuname=name.getText();
//        Date date=;
        String f_name=fname.getText();
        String m_name=mname.getText();
        String p_mobile=pmobile.getText();
        String occup=occupation.getText();
        String aadh=aadhar.getText();
        String sssm=sssmid.getText();
        String addres=address.getText();
        if(stuname.equals("")){
            JOptionPane.showMessageDialog(this,"Enter Student Name");
            name.requestFocus();
        }
        else if(f_name.equals("")){
            JOptionPane.showMessageDialog(this,"Enter Student's Father Name");
            fname.requestFocus();
        }
        else if(m_name.equals("")){
            JOptionPane.showMessageDialog(this,"Enter Student's Mother Name");
            mname.requestFocus();
        }
        else if(p_mobile.equals("")){
            JOptionPane.showMessageDialog(this,"Enter Parents Mobile No.");
            pmobile.requestFocus();
        }
        else if(occup.equals("")){
            JOptionPane.showMessageDialog(this,"Enter Father's Occupation");
            occupation.requestFocus();
        }
        else if(aadh.equals("")){
            JOptionPane.showMessageDialog(this,"Enter Student's Aadhar No");
            aadhar.requestFocus();
        }
        else if(dob.getText().equals("format yyyy/mm/dd")){
            JOptionPane.showMessageDialog(this,"Enter valid dob");
            dob.requestFocus();
        }
        else if(addres.equals("")){
            JOptionPane.showMessageDialog(this,"Enter Parmanent Address");
            address.requestFocus();
        }else{
        Student student=new Student(stuname,new Date(dob.getText()),f_name,m_name,p_mobile,occup,aadh,sssm,addres);
        
        int enrollment=StudentDao.saveStudent(student,this);
        boolean bol2=ClassDao.setStudentClass(enrollment, (String)jComboBox2.getSelectedItem());
        if(enrollment==0){
            JOptionPane.showMessageDialog(this,"Error in saving student record");
        }else if(!bol2){
            boolean success=ClassDao.setStudentClass(enrollment, (String)jComboBox2.getSelectedItem());
            if(!success){
                JOptionPane.showMessageDialog(this,"Error in saving student");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Student Saved successfully");
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void dobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobMouseClicked
            dob.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_dobMouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        tab1.setVisible(false);
        tab2.setVisible(true);
        tab3.setVisible(false);
        tab4.setVisible(false);
        tab5.setVisible(false);
//        tab6.setVisible(false);
        tab7.setVisible(false);
//        tab7.setVisible(false);
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        tab1.setVisible(true);
        tab2.setVisible(false);
        tab3.setVisible(false);
        tab4.setVisible(false);
        tab5.setVisible(false);
//        tab6.setVisible(false);
        tab7.setVisible(false);   
        ArrayList<String> list=ClassDao.getAllClass();
        String[] lst=new String[list.size()];
        for(int i=0;i<list.size();i++){
            lst[i]=list.get(i);
        }
//        System.out.println(lst[8]);
        DefaultComboBoxModel model=new DefaultComboBoxModel(lst);
        jComboBox2.setModel(model);// TODO add your handling code here:
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        tab1.setVisible(false);
        tab2.setVisible(false);
        tab3.setVisible(true);
        tab4.setVisible(false);
        tab5.setVisible(false);
//        tab6.setVisible(false);
        tab7.setVisible(false);
    ArrayList<String> list=ClassDao.getAllClass();
        String[] lst=new String[list.size()];
        for(int i=0;i<list.size();i++){
            lst[i]=list.get(i);
        }
//        System.out.println(lst[8]);
        DefaultComboBoxModel model=new DefaultComboBoxModel(lst);
        jComboBox1.setModel(model);// TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        tab1.setVisible(false);
        tab2.setVisible(false);
        tab3.setVisible(false);
        tab4.setVisible(true);
        tab5.setVisible(false);
//        tab6.setVisible(false);
        tab7.setVisible(false);
ArrayList<String> list=ClassDao.getAllClass();
        String[] lst=new String[list.size()];
        for(int i=0;i<list.size();i++){
            lst[i]=list.get(i);
        }
//        System.out.println(lst[8]);
        DefaultComboBoxModel model=new DefaultComboBoxModel(lst);
         showEdit.setVisible(false);
        jComboBox4.setModel(model);// TODO add your handling code here:
    }//GEN-LAST:event_btn4MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        tab1.setVisible(false);
        tab2.setVisible(false);
        tab3.setVisible(false);
        tab4.setVisible(false);
        tab5.setVisible(true);
//        tab6.setVisible(false);
        tab7.setVisible(false);
        tcdate.setVisible(false);
        jLabel45.setVisible(false);
ArrayList<String> list=ClassDao.getAllClass();
        String[] lst=new String[list.size()];
        for(int i=0;i<list.size();i++){
            lst[i]=list.get(i);
        }
        DefaultComboBoxModel model=new DefaultComboBoxModel(lst);
         showEdit.setVisible(false);
        jComboBox5.setModel(model);// TODO add your handling code here:
    }//GEN-LAST:event_btn6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        admin=null;
        AdminLogin adm=new AdminLogin();
        adm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void dob1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dob1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dob1MouseClicked

    private void dob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob1ActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void fathusnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathusnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathusnameActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void qualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualificationActionPerformed

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearStaffForm();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            String name=name1.getText();
            String qualific=qualification.getText();
            String mob=mobile.getText();
            String fathusn=fathusname.getText();
            String address=address1.getText();
            String pass=password.getText();
            if(name.equals("")){
                JOptionPane.showMessageDialog(this,"Enter Name");
                name1.requestFocus();
            }else if(qualific.equals("")){
                JOptionPane.showMessageDialog(this,"Enter Qualification");
                qualification.requestFocus();
            }else if(mob.equals("")){
                JOptionPane.showMessageDialog(this,"Enter Mobile No.");
                mobile.requestFocus();
            }else if(fathusn.equals("")){
                JOptionPane.showMessageDialog(this, "Enter Father or Husband Name");
                fathusname.requestFocus();
            }else if(address.equals("")){
                JOptionPane.showMessageDialog(this,"Enter Address");
                address1.requestFocus();
            }else if(pass.equals("")){
                JOptionPane.showMessageDialog(this, "Enter password");
                password.requestFocus();
            }else if(dob1.getText()=="format yyyy/mm/dd"){
                JOptionPane.showMessageDialog(this,"Enter Valid Dob");
                dob1.requestFocus();
            }else if(pass.length()>10){
                JOptionPane.showMessageDialog(this,"Password can have upto 10 character");
            }
            else {
                com.Entities.Staff staff=new com.Entities.Staff(fathusn,new Date(dob1.getText()),qualific,mob,address,name);
                StaffDao.saveStaffDetails(staff, pass, this);
                JOptionPane.showMessageDialog(this,"Staff's Details Saved successfully");
                clearStaffForm();
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tab3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_tab3MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tab3MouseWheelMoved

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
//        System.out.println(jComboBox1.getSelectedItem()=="3RD00");// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_ALL_COLUMNS);
//        TableColumn col=jTable1.getColumnModel().getColumn(0);
//        col.setPreferredWidth(100);
//        
        String year=(String)jComboBox3.getSelectedItem();
        String cls=(String)jComboBox1.getSelectedItem();
        ArrayList<Student> student=ClassDao.getAllStudentFromClass(cls,year);
        for(Student s:student){
            String[] tbRow={""+s.getEnrollment(),s.getName(),""+s.getDob(),s.getFname(),s.getMname(),s.getFoccupation(),s.getFmobile(),s.getAadhar(),s.getSssmid(),""+s.getAddmission_date(),s.getAddress(),""+s.isIsStudying(),""+s.getTcDate()};
            DefaultTableModel tb1=(DefaultTableModel)jTable1.getModel();
            tb1.addRow(tbRow);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MousePressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jComboBox4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MousePressed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Date date=new Date(fee_dob.getText());
     int enrollment=StudentDao.getEnrollmentByNameAndDobAndYear(fees_name.getText(),new java.sql.Date(date.getYear(),date.getMonth(),date.getDate()),(String)jComboBox4.getSelectedItem(),this);
     jTextField1.setText(""+enrollment);
     DefaultTableModel dfm=(DefaultTableModel)jTable2.getModel();
        
        dfm.setRowCount(0);
     double[] d=StudentDao.getTotalPayableFee((String)jComboBox4.getSelectedItem(), this);
        JTableHeader th = jTable2.getTableHeader();
        TableColumnModel tcm = th.getColumnModel();
        TableColumn tc = tcm.getColumn(2);
        tc.setHeaderValue("Installment1 Rs."+d[0] );
        th.repaint();
        tc = tcm.getColumn(4);
        tc.setHeaderValue("Installment2 Rs."+ d[1] );
        th.repaint();
        tc = tcm.getColumn(6);
        tc.setHeaderValue("Installment3 Rs."+ d[2] );
        th.repaint();
        Fees fee=StudentDao.getFeesStatus(enrollment,(String)jComboBox4.getSelectedItem(), this);
        if(fee!=null){
        String[] str={fee.getEnrollment()+"",fee.getClass_id(),fee.getInstallment1()+"",fee.getReceipt1(),fee.getInstallment2()+"",fee.getReceipt2(),fee.getInstallment3()+"",fee.getReceipt3(),fee.isClear_status()+""};
        dfm.addRow(str);
        }
//        else{
//            
//        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        showEdit.setVisible(true);
        editButton.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void enrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentActionPerformed

    private void receipt_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receipt_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receipt_noActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int instNo=Integer.parseInt((String)installmentno.getSelectedItem());
        double amount=Double.parseDouble(installment_amount.getText());
        String receipt=receipt_no.getText();
        boolean cleared=false;
        if(buttonGroup1.getSelection().getActionCommand()=="Yes"){
            cleared=true;
        }
        boolean tru=StudentDao.UpdateStatus(Integer.parseInt(enrollment.getText()),(String)jComboBox4.getSelectedItem(),instNo, amount,receipt,cleared, this);
        if(tru){
            JOptionPane.showMessageDialog(this,"Fees status Saved Success fully");
        }else{
            JOptionPane.showMessageDialog(this,"Try again status not updated");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void installment_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installment_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_installment_amountActionPerformed

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MousePressed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
          Date date=new Date(fee_dob1.getText());
          int enrollment=StudentDao.getEnrollmentByNameAndDobAndYear(fees_name1.getText(),new java.sql.Date(date.getYear(),date.getMonth(),date.getDate()),(String)jComboBox5.getSelectedItem(),this);
          jTextField2.setText(""+enrollment);
          Student student=StudentDao.getStudentFromEnrollment(enrollment, this);
          addmissiondt.setText(student.getAddmission_date().toString().split("-")[0]+"/"+student.getAddmission_date().toString().split("-")[1]+"/"+student.getAddmission_date().toString().split("-")[2]);
          upfathern.setText(student.getFname());
          upmothern.setText(student.getMname());
          upfathermob.setText(student.getFmobile());
          upfatheroc.setText(student.getFoccupation());
          upaadhar.setText(student.getAadhar());
          upsssmid.setText(student.getSssmid());
          upaddress.setText(student.getAddress());
          if(!student.isIsStudying()){
              tcdate.setVisible(true);
              tcdate.setText(student.getTcDate().getYear()+"/"+student.getTcDate().getMonth()+"/"+student.getTcDate().getDate());
          }else{
              tcdate.setEnabled(true);
              tcdate.setVisible(true);
              jLabel45.setVisible(true);
          }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void editButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButton1ActionPerformed
          Date tcDate=null;
          if(!tcdate.getText().equals("")){
           tcDate=new Date(tcdate.getText());
          }else{
              tcDate=new Date("2030/10/04");
          }
          Date date=new Date(fee_dob1.getText());
        Student student = new Student(Integer.parseInt(jTextField2.getText()),fees_name1.getText(),new java.sql.Date(date.getYear(),date.getMonth(),date.getDate()), upfathern.getText(),upmothern.getText(),upfathermob.getText(),upfatheroc.getText(),upaadhar.getText(),upsssmid.getText(),true,tcDate,upaddress.getText(),new java.sql.Date(new Date(addmissiondt.getText()).getYear(),new Date(addmissiondt.getText()).getMonth(),new Date(addmissiondt.getText()).getDate()));
        if(StudentDao.updateStudent(student, this)){
            JOptionPane.showMessageDialog(this,"Student updates successfully");
        }
    }//GEN-LAST:event_editButton1ActionPerformed

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        tab1.setVisible(false);
        tab2.setVisible(false);
        tab3.setVisible(false);
        tab4.setVisible(false);
        tab5.setVisible(false);
        tab8.setVisible(true);
        tab7.setVisible(false);
        ArrayList<Staff> staff=StaffDao.getAllStaff(this);
        String[] stf=new String[staff.size()];
        for(int i=0;i<staff.size();i++){
            stf[i]=staff.get(i).getStaffId()+" "+staff.get(i).getName();
        }
        DefaultComboBoxModel model=new DefaultComboBoxModel(stf);
        jComboBox7.setModel(model);
        ArrayList<String> list=ClassDao.getAllClass();
        String[] lst=new String[list.size()];
        for(int i=0;i<list.size();i++){
            lst[i]=list.get(i);
        }
        model=new DefaultComboBoxModel(lst);
        jComboBox6.setModel(model);
    }//GEN-LAST:event_btn5MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        boolean b=false;
        String class_id=(String)jComboBox6.getSelectedItem();
        int staffid=Integer.parseInt( ((String)jComboBox7.getSelectedItem()).split(" ")[0]);
        int bt=JOptionPane.showConfirmDialog(this,"Current Class Teacher is "+ StaffDao.getStaffNameFromStaffId(ClassDao.getClassTeacher(class_id, this),this));
        if(bt==0){
            ClassDao.setClassTeacher(class_id, staffid,this);
        }
    }//GEN-LAST:event_jButton9ActionPerformed
public void clearStaffForm(){
    name1.setText("");
            qualification.setText("");
            mobile.setText("");
            fathusname.setText("");
            address1.setText("");
            password.setText("");
            dob1.setText("");
}
    /**
     * @param args the command line arguments
     */
    public void clear(){
        name.setText("");
//        name.getText();
        dob.setText("");
        fname.setText("");
        mname.setText("");
        pmobile.setText("");
        occupation.setText("");
        aadhar.setText("");
        sssmid.setText("");
        address.setText("");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar;
    private javax.swing.JTextField addmissiondt;
    private javax.swing.JTextField address;
    private javax.swing.JTextField address1;
    private javax.swing.JLabel btn1;
    private javax.swing.JLabel btn2;
    private javax.swing.JLabel btn3;
    private javax.swing.JLabel btn4;
    private javax.swing.JLabel btn5;
    private javax.swing.JLabel btn6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField dob1;
    private javax.swing.JRadioButton due_cleared;
    private javax.swing.JRadioButton due_not;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editButton1;
    private javax.swing.JTextField enrollment;
    private javax.swing.JTextField fathusname;
    private javax.swing.JTextField fee_dob;
    private javax.swing.JTextField fee_dob1;
    private javax.swing.JTextField fees_name;
    private javax.swing.JTextField fees_name1;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField installment_amount;
    private javax.swing.JComboBox<String> installmentno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField occupation;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField pmobile;
    private javax.swing.JTextField qualification;
    private javax.swing.JTextField receipt_no;
    private javax.swing.JPanel showEdit;
    private javax.swing.JTextField sssmid;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab7;
    private javax.swing.JPanel tab8;
    private javax.swing.JTextField tcdate;
    private javax.swing.JTextField upaadhar;
    private javax.swing.JTextArea upaddress;
    private javax.swing.JTextField upfathermob;
    private javax.swing.JTextField upfathern;
    private javax.swing.JTextField upfatheroc;
    private javax.swing.JTextField upmothern;
    private javax.swing.JTextField upsssmid;
    // End of variables declaration//GEN-END:variables
}
