/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.schoolmanagment;
import com.Daos.ClassDao;
import com.Daos.StudentDao;
import com.Daos.SubjectMarksDao;
import com.Entities.Staff;
import com.Entities.Student;
import java.awt.Cursor;
import java.util.Date;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import com.Entities.SubjectMarks;
/**
 *
 * @author DELL
 */
public class StaffDashboard extends javax.swing.JFrame {

    private static Staff staff; 
    private static  String class_id;
    public static String[] exam_name;
    public static HashMap<String,Integer> exam_max;
    /**
     * Creates new form StaffDashboard
     */
    public StaffDashboard() {
        initComponents();
        this.setResizable(false);
        this.setBounds(300,100,805,588);
        this.setTitle("Staff's Dashboard");
        staff_tab3.setVisible(false);
        staff_tab5.setVisible(false);
        staff_tab7.setVisible(true);
        staff_tab8.setVisible(false);
         btn5.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn3.setCursor(new Cursor(Cursor.HAND_CURSOR));
         jLabel3.setCursor(new Cursor(Cursor.HAND_CURSOR));
       btn6.setCursor(new Cursor(Cursor.HAND_CURSOR));
        exam_name=new String[]{"UNIT-1","UNIT-2","UNIT-3","UNIT-4","QUATERLY","HALFYEARLY","FINAL"};
        exam_max=new HashMap<String,Integer>();
        exam_max.put("UNIT-1",100);
        exam_max.put("UNIT-2",100);
        exam_max.put("UNIT-3",100);
        exam_max.put("UNIT-4",100);
        exam_max.put("QUATERLY",100);
        exam_max.put("HALFYEARLY",100);
        exam_max.put("FINAL",100);
//        System.out.println(exam_max);
    }
    public StaffDashboard(Staff stf){
        this();
        StaffDashboard.staff=stf;
        class_id=ClassDao.getClassIdFromClassTeacher(staff.getStaffId(),this);
        name.setText(staff.getName());
//        String classId=
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn3 = new javax.swing.JLabel();
        btn5 = new javax.swing.JLabel();
        btn6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        staff_tab8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        cls_id = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        exams = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        staff_tab7 = new javax.swing.JPanel();
        staff_tab3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        exm_name = new javax.swing.JComboBox<>();
        subject_name = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        enrollment = new javax.swing.JTextField();
        marks_obtn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        out_of = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        staff_tab5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        fees_name1 = new javax.swing.JTextField();
        fee_dob1 = new javax.swing.JTextField();
        editButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        addmissiondt = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        upfathern = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        upmothern = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        upfathermob = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        upfatheroc = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        upaadhar = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        upsssmid = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        upaddress = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        tcdate = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 110, 70));

        name.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 204));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 150, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("LOGOUT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("School Management System");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 70));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Staff");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 60, 30));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3.setBackground(new java.awt.Color(153, 0, 153));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 204, 204));
        btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn3.setText("Student Academics");
        btn3.setOpaque(true);
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 50));

        btn5.setBackground(new java.awt.Color(153, 0, 153));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 204, 204));
        btn5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn5.setText("Update Student");
        btn5.setOpaque(true);
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 50));

        btn6.setBackground(new java.awt.Color(153, 0, 153));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 204, 204));
        btn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn6.setText("Get Marks Details");
        btn6.setOpaque(true);
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 50));

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staff_tab8.setBackground(new java.awt.Color(204, 153, 255));
        staff_tab8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setText("Enter Student Details");
        jPanel7.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 30));

        cls_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cls_idItemStateChanged(evt);
            }
        });
        cls_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cls_idMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cls_idMousePressed(evt);
            }
        });
        cls_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cls_idActionPerformed(evt);
            }
        });
        jPanel7.add(cls_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 180, 30));

        jButton9.setText("GET DETAILS");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 130, 30));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(jTable1);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1040, 270));

        exams.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                examsItemStateChanged(evt);
            }
        });
        exams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                examsMousePressed(evt);
            }
        });
        exams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examsActionPerformed(evt);
            }
        });
        jPanel7.add(exams, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 180, 30));

        jScrollPane1.setViewportView(jPanel7);

        staff_tab8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 630, 400));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Marks List");
        staff_tab8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 220, 70));

        jPanel3.add(staff_tab8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        staff_tab7.setBackground(new java.awt.Color(204, 153, 255));
        staff_tab7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(staff_tab7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        staff_tab3.setBackground(new java.awt.Color(204, 153, 255));
        staff_tab3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                staff_tab3MouseWheelMoved(evt);
            }
        });
        staff_tab3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Exam Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 30));

        exm_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(exm_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 190, 30));

        subject_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(subject_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 190, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Subject");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Enrollment");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 30));

        enrollment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(enrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, 30));

        marks_obtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(marks_obtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Marks Obtained");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 110, 30));

        out_of.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(out_of, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 150, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Out Of");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 110, 30));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 230, 40));

        jScrollPane2.setViewportView(jPanel2);

        staff_tab3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 410));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update Student's Marks");
        staff_tab3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 330, 60));

        jPanel3.add(staff_tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        staff_tab5.setBackground(new java.awt.Color(204, 153, 255));
        staff_tab5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("Enter Student Details");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 30));

        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox5MousePressed(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 180, 30));

        jButton8.setText("GET DETAILS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 130, 30));

        fees_name1.setText("Enter Name");
        jPanel6.add(fees_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 190, 30));

        fee_dob1.setText("yyyy/mm/dd");
        jPanel6.add(fee_dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, 30));

        editButton1.setText("UPDATE STATUS");
        editButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(editButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 140, 40));

        jTextField2.setEnabled(false);
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, 30));

        jLabel41.setText("Enrollment");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        addmissiondt.setEnabled(false);
        jPanel6.add(addmissiondt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, 30));

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("ADDMISSION DATE");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 30));

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("FATHER NAME");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 120, 30));
        jPanel6.add(upfathern, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, 30));

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("MOTHER NAME");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 120, 30));
        jPanel6.add(upmothern, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 180, 30));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("FATHER MOBILE");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 120, 30));
        jPanel6.add(upfathermob, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 180, 30));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("FATHER OCCUPATION");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 30));
        jPanel6.add(upfatheroc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 180, 30));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("AADHAR NO");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 120, 30));
        jPanel6.add(upaadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 180, 30));

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("SSSMID");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 120, 30));
        jPanel6.add(upsssmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 180, 30));

        upaddress.setColumns(20);
        upaddress.setRows(5);
        jScrollPane6.setViewportView(upaddress);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 180, 80));

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("ADDRESS");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 120, 30));

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("TC_DATE");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 120, 30));

        tcdate.setEnabled(false);
        jPanel6.add(tcdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 180, 30));

        jScrollPane5.setViewportView(jPanel6);

        staff_tab5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 630, 390));

        jLabel46.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("UPDATE STUDENT");
        staff_tab5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 260, 80));

        jPanel3.add(staff_tab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        staff=null;
        AdminLogin adm=new AdminLogin();
        adm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        staff_tab3.setVisible(true);
        staff_tab5.setVisible(false);
        staff_tab7.setVisible(false);
        staff_tab8.setVisible(false);
//        ArrayList<String> list=ClassDao.getAllClass();
//        String[] lst=new String[list.size()];
//        for(int i=0;i<list.size();i++){
//            lst[i]=list.get(i);
//        }
        DefaultComboBoxModel model=new DefaultComboBoxModel(exam_name);
        exm_name.setModel(model);
        ArrayList<String> subjectlst=SubjectMarksDao.getSubjectsName(StaffDashboard.class_id, this);
        String[] sublst=new String[subjectlst.size()];
        for(int i=0;i<subjectlst.size();i++){
            sublst[i]=subjectlst.get(i);
            System.out.println(sublst[i]);
        }
        System.out.println(subjectlst);
        model=new DefaultComboBoxModel(sublst);
        subject_name.setModel(model);
    }//GEN-LAST:event_btn3MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        
        staff_tab3.setVisible(false);
        staff_tab5.setVisible(true);
        staff_tab7.setVisible(false);
        staff_tab8.setVisible(false);
        tcdate.setVisible(false);
        jLabel45.setVisible(false);
        ArrayList<String> list=ClassDao.getAllClass();
        String[] lst=new String[list.size()];
        for(int i=0;i<list.size();i++){
            lst[i]=list.get(i);
        }
        DefaultComboBoxModel model=new DefaultComboBoxModel(lst);
//        showEdit.setVisible(false);
        jComboBox5.setModel(model);// TODO add your handling code here:
    }//GEN-LAST:event_btn5MouseClicked

    private void staff_tab3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_staff_tab3MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_tab3MouseWheelMoved

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MousePressed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Date date=new Date(fee_dob1.getText());
        int enrollment=StudentDao.getEnrollmentByNameAndDobAndYear(fees_name1.getText(),new java.sql.Date(date.getYear(),date.getMonth(),date.getDate()),(String)jComboBox5.getSelectedItem(),this);
        jTextField2.setText(""+enrollment);
        Student student=StudentDao.getStudentFromEnrollment(enrollment, this);
        addmissiondt.setText(student.getAddmission_date().toString().split("-")[0]+"/"+student.getAddmission_date().toString().split("-")[1]+"/"+student.getAddmission_date().toString().split("-")[2]);
        upfathern.setText(student.getFname());
        upmothern.setText(student.getMname());
        upfathermob.setText(student.getFmobile());
        upfatheroc.setText(student.getFoccupation());
        upaadhar.setText(student.getAadhar());
        upsssmid.setText(student.getSssmid());
        upaddress.setText(student.getAddress());
        if(!student.isIsStudying()){
            tcdate.setVisible(true);
            tcdate.setText(student.getTcDate().getYear()+"/"+student.getTcDate().getMonth()+"/"+student.getTcDate().getDate());
        }else{
            tcdate.setEnabled(true);
            tcdate.setVisible(true);
            jLabel45.setVisible(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void editButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButton1ActionPerformed
        Date tcDate=null;
        if(!tcdate.getText().equals("")){
            tcDate=new Date(tcdate.getText());
        }else{
            tcDate=new Date("2030/10/04");
        }
        Date date=new Date(fee_dob1.getText());
        Student student = new Student(Integer.parseInt(jTextField2.getText()),fees_name1.getText(),new java.sql.Date(date.getYear(),date.getMonth(),date.getDate()), upfathern.getText(),upmothern.getText(),upfathermob.getText(),upfatheroc.getText(),upaadhar.getText(),upsssmid.getText(),true,tcDate,upaddress.getText(),new java.sql.Date(new Date(addmissiondt.getText()).getYear(),new Date(addmissiondt.getText()).getMonth(),new Date(addmissiondt.getText()).getDate()));
        if(StudentDao.updateStudent(student, this)){
            JOptionPane.showMessageDialog(this,"Student updates successfully");
        }
    }//GEN-LAST:event_editButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(SubjectMarksDao.updateMarksStatus(Integer.parseInt(enrollment.getText()),class_id, (String)subject_name.getSelectedItem(),Float.parseFloat(marks_obtn.getText()), (String)exm_name.getSelectedItem(), Float.parseFloat(out_of.getText()), this)){
            JOptionPane.showMessageDialog(this,"Student's Marks Updated Successfully");
        }else{
            JOptionPane.showMessageDialog(this,"Error in updating record try again.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        staff_tab3.setVisible(false);
        staff_tab5.setVisible(false);
        staff_tab7.setVisible(false);
        staff_tab8.setVisible(true);
        ArrayList<String> list=ClassDao.getAllClass();
        String[] lst=new String[list.size()];
        for(int i=0;i<list.size();i++){
            lst[i]=list.get(i);
        }
        DefaultComboBoxModel model=new DefaultComboBoxModel(lst);
        cls_id.setModel(model);
        model=new DefaultComboBoxModel(exam_name);
        exams.setModel(model);
    }//GEN-LAST:event_btn6MouseClicked

    private void cls_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cls_idItemStateChanged
       ArrayList<String> subjectlst=SubjectMarksDao.getSubjectsName(StaffDashboard.class_id, this);
        String[] sublst=new String[subjectlst.size()];
        for(int i=0;i<subjectlst.size();i++){
            sublst[i]=subjectlst.get(i);
            System.out.println(sublst[i]);
        }
        DefaultComboBoxModel model=new DefaultComboBoxModel(sublst);
    }//GEN-LAST:event_cls_idItemStateChanged

    private void cls_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cls_idMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cls_idMouseClicked

    private void cls_idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cls_idMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cls_idMousePressed

    private void cls_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cls_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cls_idActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ArrayList<String> subjectlst=SubjectMarksDao.getSubjectsName((String)cls_id.getSelectedItem(), this);
        System.out.println();
        String a[]=new String[(subjectlst.size())*2+5];
        int couter=0;
        a[0]="Enrollment";
        a[1]="Name";
        for(int i=2;i<a.length-3;i++){
            if(i%2!=0)
            a[i]="Out Of";
            else if(couter<subjectlst.size()){
                a[i]=subjectlst.get(couter);
                couter++;
            }
        }
        a[(subjectlst.size())*2+2]="Total";
        a[(subjectlst.size())*2+3]="Out Off";
        a[(subjectlst.size())*2+4]="Average";
        boolean canEdit[]=new boolean[a.length];
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
                a
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [a.length];
//            public Class getColumnClass(int columnIndex) {
//                return types [columnIndex];
//            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
            for(int i=0;i<a.length;i++){
            TableColumn tc = jTable1.getColumnModel().getColumn(i);
            tc.sizeWidthToFit();
            }
            HashMap<Integer,HashMap<String,Float>> result=SubjectMarksDao.getAllSubjectMarks((String)cls_id.getSelectedItem(),(String)exams.getSelectedItem(), this);
            DefaultTableModel dfm=(DefaultTableModel)jTable1.getModel();
            String[] str;
            int outof=exam_max.get(exams.getSelectedItem());
            ArrayList<String> rows=new ArrayList<>();
            String s=new String();
            for(Integer key:result.keySet()){
                HashMap<String,Float> temp=result.get(key);
                s+=key;
                s+=":"+StudentDao.getStudentFromEnrollment(key, this).getName();
                int count=subjectlst.size();
                int total=0;
                for(String subject:subjectlst){
                    total+=temp.get(subject);
                    s+=":"+temp.get(subject);
                    s+=":"+outof;
                }
                s+=":"+total;
                s+=":"+outof*subjectlst.size();
                s+=":"+String.format("%.2f",(float)total/(outof*subjectlst.size()));
                str=s.split(":");
                s="";
               dfm.addRow(str);
          }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void examsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_examsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_examsItemStateChanged

    private void examsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_examsMouseClicked

    private void examsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_examsMousePressed

    private void examsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examsActionPerformed
    public String getClassId(){
        return ClassDao.getClassIdFromClassTeacher(staff.getStaffId(), this);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addmissiondt;
    private javax.swing.JLabel btn3;
    private javax.swing.JLabel btn5;
    private javax.swing.JLabel btn6;
    private javax.swing.JComboBox<String> cls_id;
    private javax.swing.JButton editButton1;
    private javax.swing.JTextField enrollment;
    private javax.swing.JComboBox<String> exams;
    private javax.swing.JComboBox<String> exm_name;
    private javax.swing.JTextField fee_dob1;
    private javax.swing.JTextField fees_name1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField marks_obtn;
    private javax.swing.JLabel name;
    private javax.swing.JTextField out_of;
    private javax.swing.JPanel staff_tab3;
    private javax.swing.JPanel staff_tab5;
    private javax.swing.JPanel staff_tab7;
    private javax.swing.JPanel staff_tab8;
    private javax.swing.JComboBox<String> subject_name;
    private javax.swing.JTextField tcdate;
    private javax.swing.JTextField upaadhar;
    private javax.swing.JTextArea upaddress;
    private javax.swing.JTextField upfathermob;
    private javax.swing.JTextField upfathern;
    private javax.swing.JTextField upfatheroc;
    private javax.swing.JTextField upmothern;
    private javax.swing.JTextField upsssmid;
    // End of variables declaration//GEN-END:variables
}
